
GET http://localhost:5240/

# Get all category
###
GET http://localhost:5240/api/categories

# Single category
###
GET http://localhost:5240/api/categories/7bd55267-3bf5-401c-a737-09bfa94f4fc9

# Create category
###
POST http://localhost:5240/api/categories
Content-Type: application/json

{
  "name": "Category 4",
  "description": "Description 1"
}
###
PUT  http://localhost:5240/api/categories/bebec5ed-e1ed-472c-9a53-a7f24a07f22b
Content-Type: application/json

{
  "name": "Adnan",
  "description": "Description 1"
}



# Delete category
### 
DELETE http://localhost:5240/api/categories/c9363043-0d6e-45f7-92b0-8d497d51b957