
GET http://localhost:5240/


# Start Category API

# Get all category
###
GET http://localhost:5240/api/categories

# Single category
###
GET http://localhost:5240/api/categories/5ec33a71-8469-42f0-a954-455948dd3fce



# Create category
###
POST http://localhost:5240/api/categories
Content-Type: application/json

{
  "name": "book",
  "description": "Description 1"
}


###
PUT  http://localhost:5240/api/categories/5ec33a71-8469-42f0-a954-455948dd3fce
Content-Type: application/json

{
  "name": "Adnan",
  "description": "Description 1"
}

# Delete category
### 
DELETE http://localhost:5240/api/categories/a30999e6-7b20-498a-8b70-483d611c3c29

###
GET  http://localhost:5240/api/categories
###
GET  http://localhost:5240/api/categories?searchValue=book

# End Category API