### Base URL
GET http://localhost:5240/

# Start Category API

### Get all categories
GET http://localhost:5240/api/categories

### Get a single category by ID
GET http://localhost:5240/api/categories/87f01c4b-c15c-426c-877b-0f01c0de5c94

### Create a new category
POST http://localhost:5240/api/categories
Content-Type: application/json

{
  "name": "Book",
  "description": "A category for books"
}

### Update an existing category
PUT http://localhost:5240/api/categories/e6444ca6-cf2c-49c2-821a-84568429453a
Content-Type: application/json

{
  "name": "Updated Name",
  "description": "Updated description"
}

### Delete a category
DELETE http://localhost:5240/api/categories/87f01c4b-c15c-426c-877b-0f01c0de5c94

### Search categories by name
GET http://localhost:5240/api/categories?searchValue=book

# End Category API
